"""deeplearning-opj.ipynb
Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/drive/1nb-2DGj2Wz5s9EuvxcCGC4Xn7ZST0CDi
"""

from google.colab import files
files.upload()

print(train_df.head())
print(train_df.columns)

import pandas as pd

train_df = pd.read_csv("train_3.csv", sep=";")
valid_df = pd.read_csv("validation_3.csv", sep=";")
test_df = pd.read_csv("test_3.csv", sep=";")

print(train_df.head())

train_df = train_df.dropna(subset=["text"])
valid_df = valid_df.dropna(subset=["text"])
test_df = test_df.dropna(subset=["text"])

import torch

label_map = {
    "negative": 0,
    "neutral": 1,
    "positive": 2,
    "mixed": 3,
    "sarcastic": 4
}

train_df["label"] = train_df["label"].astype(str).str.strip().map(label_map)
valid_df["label"] = valid_df["label"].astype(str).str.strip().map(label_map)
test_df["label"] = test_df["label"].astype(str).str.strip().map(label_map)
train_df = train_df.dropna(subset=["label"])
valid_df = valid_df.dropna(subset=["label"])
test_df = test_df.dropna(subset=["label"])

train_y = torch.tensor(train_df["label"].values)
val_y   = torch.tensor(valid_df["label"].values)
test_y  = torch.tensor(test_df["label"].values)

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

vectorizer = CountVectorizer()

X_train = vectorizer.fit_transform(train_df["text"])
X_valid = vectorizer.transform(valid_df["text"])
X_test = vectorizer.transform(test_df["text"])

y_train = train_df["label"]
y_test = test_df["label"]

model = MultinomialNB()
model.fit(X_train, y_train)
pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

from collections import Counter

all_text = " ".join(train_df["text"].astype(str)).lower().split()
counts = Counter(all_text)

vocab = sorted(counts, key=counts.get, reverse=True)
vocab_to_int = {word: i+1 for i, word in enumerate(vocab)}

def encode(df):
    reviews = []

    for text in df["text"].astype(str):
        reviews.append([vocab_to_int.get(word, 0) for word in text.lower().split()])

    return reviews

train_x = encode(train_df)
val_x = encode(valid_df)
test_x = encode(test_df)

import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader

# -------- PAD --------
def pad(reviews, seq_length=200):
    features = np.zeros((len(reviews), seq_length), dtype=int)

    for i, row in enumerate(reviews):
        features[i, -len(row):] = np.array(row)[:seq_length]

    return features

train_x = pad(train_x)
val_x   = pad(val_x)
test_x  = pad(test_x)

# -------- TENSOR KONVERZIJA --------
train_x = torch.tensor(train_x, dtype=torch.long)
val_x   = torch.tensor(val_x, dtype=torch.long)
test_x  = torch.tensor(test_x, dtype=torch.long)

train_y = torch.tensor(train_df["label"].values, dtype=torch.long)
val_y   = torch.tensor(valid_df["label"].values, dtype=torch.long)
test_y  = torch.tensor(test_df["label"].values, dtype=torch.long)

# -------- DATALOADER --------
batch_size = 50

train_data = TensorDataset(train_x, train_y)
val_data   = TensorDataset(val_x, val_y)
test_data  = TensorDataset(test_x, test_y)

train_loader = DataLoader(train_data, batch_size=batch_size, shuffle=True)
val_loader   = DataLoader(val_data, batch_size=batch_size)
test_loader  = DataLoader(test_data, batch_size=batch_size)

print(train_x.shape)
print(train_y.shape)

import torch.nn as nn

class SentimentLSTM(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, n_layers, output_size, drop_prob=0.5):
        super().__init__()

        self.embedding = nn.Embedding(vocab_size, embedding_dim)

        self.lstm = nn.LSTM(
            embedding_dim,
            hidden_dim,
            n_layers,
            batch_first=True,
            dropout=drop_prob
        )

        self.dropout = nn.Dropout(0.3)
        self.fc = nn.Linear(hidden_dim, output_size)

    def forward(self, x):

        x = x.long()
        embeds = self.embedding(x)

        lstm_out, _ = self.lstm(embeds)

        out = lstm_out[:, -1, :]
        out = self.dropout(out)
        out = self.fc(out)

        return out

vocab_size = len(vocab_to_int) + 1
embedding_dim = 400
hidden_dim = 256
n_layers = 2
output_size = 5

lstm_net = SentimentLSTM(vocab_size, embedding_dim, hidden_dim, n_layers, output_size)

print(lstm_net)

len(train_loader.dataset)

import torch
import torch.nn as nn
import torch.optim as optim

net = lstm_net
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(net.parameters(), lr=0.001)

epochs = 4

for e in range(epochs):
    net.train()

    for inputs, labels in train_loader:

        optimizer.zero_grad()

        outputs = net(inputs)

        loss = criterion(outputs, labels)

        loss.backward()
        optimizer.step()

    print(f"Epoch {e+1} done")

class SentimentGRU(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, n_layers, output_size, drop_prob=0.5):
        super().__init__()

        self.hidden_dim = hidden_dim
        self.n_layers = n_layers

        self.embedding = nn.Embedding(vocab_size, embedding_dim)

        self.gru = nn.GRU(
            embedding_dim,
            hidden_dim,
            n_layers,
            batch_first=True,
            dropout=drop_prob
        )

        self.dropout = nn.Dropout(0.3)
        self.fc = nn.Linear(hidden_dim, output_size)

    def forward(self, x):
        x = x.long()
        embeds = self.embedding(x)

        gru_out, _ = self.gru(embeds)

        out = gru_out[:, -1, :]
        out = self.dropout(out)
        out = self.fc(out)

        return out

vocab_size = len(vocab_to_int) + 1
output_size = 5
embedding_dim = 400
hidden_dim = 256
n_layers = 2

gru_net = SentimentGRU(vocab_size, embedding_dim, hidden_dim, n_layers, output_size)

print(gru_net)

import torch
import torch.nn as nn
import torch.optim as optim

net = gru_net
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(net.parameters(), lr=0.001)

for e in range(epochs):
    net.train()

    for inputs, labels in train_loader:

        optimizer.zero_grad()

        outputs = net(inputs)

        loss = criterion(outputs, labels)

        loss.backward()
        optimizer.step()

    print(f"Epoch {e+1} done")

import torch
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

lstm_net.eval()

all_preds = []
all_labels = []

with torch.no_grad():
    for inputs, labels in test_loader:

        outputs = lstm_net(inputs)

        preds = torch.argmax(outputs, dim=1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

print("LSTM RESULTS")
print("----------------------")
print("Accuracy:", accuracy_score(all_labels, all_preds))

print("\nClassification report:\n")
print(classification_report(all_labels, all_preds))

print("\nConfusion matrix:\n")
print(confusion_matrix(all_labels, all_preds))

gru_net.eval()

all_preds = []
all_labels = []

with torch.no_grad():
    for inputs, labels in test_loader:

        outputs = gru_net(inputs)

        preds = torch.argmax(outputs, dim=1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

print("GRU RESULTS")
print("----------------------")
print("Accuracy:", accuracy_score(all_labels, all_preds))

print("\nClassification report:\n")
print(classification_report(all_labels, all_preds))

print("\nConfusion matrix:\n")
print(confusion_matrix(all_labels, all_preds))

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

def evaluate(model):
    model.eval()

    preds_list = []
    labels_list = []

    with torch.no_grad():
        for inputs, labels in test_loader:

            outputs = model(inputs)

            preds = torch.argmax(outputs, dim=1)

            preds_list.extend(preds.cpu().numpy())
            labels_list.extend(labels.cpu().numpy())

    print("Accuracy:", accuracy_score(labels_list, preds_list))
    print(classification_report(labels_list, preds_list))
    print(confusion_matrix(labels_list, preds_list))

evaluate(lstm_net)

evaluate(gru_net)

torch.save(lstm_net.state_dict(), "lstm_model.pth")
torch.save(gru_net.state_dict(), "gru_model.pth")

from google.colab import files
files.download("lstm_model.pth")
files.download("gru_model.pth")
